version: '3.4'

services:
  react-playground:
    image: react-playground
    build: .
    environment:
      NODE_ENV: development
      CI: "true"
    ports:
      - 3000
      - 9009
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 src/index.tsx
