version: '3.4'

services:
  react-v3:
    image: react-v3
    build: .
    environment:
      NODE_ENV: development
      CI: "true"
    ports:
      - 3000
      - 9009:9009
    command: npm run storybook